name: validate and push
on:
  push:
    branches:
      - main
jobs:
  validate-zip-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4
      - name: ðŸ‘‰ðŸ‘ˆ zip
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: resources/
          dest: resources.zip
      - name: ðŸ“‚ Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_HOST }}
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './resources.zip'
          remote_path: '/home/SimpleSMP/server/'
      - name: ðŸ–¥ï¸ RCON Connection
        uses: Plagiatus/RCON-Action@v0.2
        with:
          server: 88.99.191.241
          port: 50719
          password: 3m?,yKDÂ£oe4Tu(+}Z>\:DUvB8Xf07f
          commands: '["reload", "pack set \"http://88.99.191.241:25566\" push"]'
